// A list of emotions and their instructions
EMOTIONS = [
	['Affection', ''],
	['Disgust', ''],
	// ['Intrigue', ''],
	// ['Relaxation', ''],
	// ['Agitation', ''],
	// ['Distrust', ''],
	// ['Judgment', ''],
	// ['Satisfaction', ''],
	// ['Alarm', ''],
	// ['Dominance', ''],
	// ['Laziness', ''],
	// ['Self-consciousness', ''],
	// ['Anticipation', ''],
	// ['Drunkenness', ''],
	// ['Lethargy', ''],
	// ['Self-pity', ''],
	// ['Attention', ''],
	// ['Contemplation', ''],
	// ['Lust', ''],
	// ['Seriousness', ''],
	// ['Awareness', ''],
	// ['Earnestness', ''],
	// ['Nervousness', ''],
	// ['Skepticism', ''],
	// ['Awe', ''],
	// ['Ecstasy', ''],
	// ['Objectivity', ''],
	// ['Sleepiness', ''],
	// ['Belief', ''],
	// ['Embarrassment', ''],
	// ['Opinion', ''],
	// ['Stupor', ''],
	// ['Cognition', ''],
	// ['Exaltation', ''],
	// ['Patience', ''],
	// ['Subordination', ''],
	// ['Consciousness', ''],
	// ['Exhaustion', ''],
	// ['Peacefulness', ''],
	// ['Thought', ''],
	// ['Craziness', ''],
	// ['Fatigue', ''],
	// ['Pensiveness', ''],
	// ['Trance', ''],
	// ['Curiosity', ''],
	// ['Friendliness', ''],
	// ['Pity', ''],
	// ['Transcendence', ''],
	// ['Decision', ''],
	// ['Imagination', ''],
	// ['Planning', ''],
	// ['Uneasiness', ''],
	// ['Desire', ''],
	// ['Insanity', ''],
	// ['Playfulness', ''],
	// ['Weariness', ''],
	// ['Disarray', ''],
	// ['Inspiration', ''],
	// ['Reason', ''],
	// ['Worry', '']
];

RANDOMIZE = true;

INCOMPLETE_ALERT = 'Please rate the emotional intensity in the second month.';
FINISH_ALERT = 'Thank you for participating!';
